// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rotszngyxjjqtitdluvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvdHN6bmd5eGpqcXRpdGRsdXZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMTMyODQsImV4cCI6MjA2NDU4OTI4NH0.4pFKIxvTvQClLM7jhURGqX07a1N07g3m8SsJBSgnfao";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);